-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 14:50:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goods` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `gname` VARCHAR(20) NOT NULL,
  `gprice` DECIMAL(18,2) NOT NULL,
  `gnum` INT NOT NULL,
  PRIMARY KEY (`gid`),
  UNIQUE INDEX `gname_UNIQUE` (`gname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salesman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salesman` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `sname` VARCHAR(10) NOT NULL,
  `spassword` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`sid`),
  UNIQUE INDEX `sname_UNIQUE` (`sname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GSales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GSales` (
  `gsid` INT NOT NULL AUTO_INCREMENT,
  `gid` INT NOT NULL,
  `sid` INT NOT NULL,
  `sdate` DATE NOT NULL,
  `snum` INT NOT NULL,
  INDEX `gid_idx` (`gid` ASC),
  INDEX `sid_idx` (`sid` ASC),
  PRIMARY KEY (`gsid`),
  CONSTRAINT `gid`
    FOREIGN KEY (`gid`)
    REFERENCES `mydb`.`Goods` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `mydb`.`Salesman` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
